name: Clans
author: Arjenpro
version: 1.0
main: org.guildcraft.annihilation.clans.Clans
commands:
    clan:
       aliases: [c,clans]
    chat:
    clanchat:
      aliases: [cc]
    aclan:
